### ISSUE TITLE
variable replacement in download-sucatalog.sh script

### ISSUE THREAD

**Issue by K3ll3r** [grahampugh/osx-scripts#4]
Hi Graham! Thanks for all your work on this, and everything else you've done for the mac admin community. I was going over your recent blog post, and think I noticed an error in your script.

https://github.com/grahampugh/osx-scripts/blob/20ab12ce37d027372f265827f67e692c4f1cdf91/check-xprotect-version/download-xprotect-info.sh#L33

Without an escaping backslash, this variable, $xProtectURL gets replaced as blank in my testing. Here's the relevant line in the /Library/Scripts/download-sucatalog.sh file which is created by the script:

>     curl -s "" > "/var/sucatalog/XProtectPlistConfigData.pkm"

It can be fixed by simply changing the line in your "download-xprotect-info.sh" script to `curl -s "\$xProtectURL" > "$XPROTECT_PKM_CACHE"`

**Comment by grahampugh** [comment]
Thanks, good spot.  I've made the correction as suggested.
